# Config file for podsync

[server]
# Address the server will bind to
address = ":8080"

# Directory where downloaded files will be saved
download_dir = "/opt/build/repo/downloads" # change this to the Netlify build directory

# URL for the server, used to generate feed URLs
base_url = "https://catchfirepodcast.netlify.app" # change this to your Netlify app URL

# Number of episodes to include in each feed
episode_limit = 10

# Number of days to look back when checking for new episodes
lookback_days = 7

# Enable or disable the server's logging
log_enabled = true

# Level of server logging
log_level = "info"

# Set to true to serve files over HTTPS
ssl_enabled = false

# Path to SSL certificate file
ssl_cert = ""

# Path to SSL key file
ssl_key = ""

[feeds]
[[feeds.feed1]]
# URL of the original podcast feed
url = "https://www.youtube.com/feeds/videos.xml?playlist_id=PL77wUH3sO_auKlIMhoJKXvBB5sH7vXznX" # change this to the YouTube playlist feed URL

# Path to the new feed file (relative to download_dir)
feed_file = "feed1.xml"

# Maximum number of episodes to download (-1 for unlimited)
max_episodes = 2

# Minimum interval between downloads (in hours)
interval = 12

# Enable or disable feed-specific logging
log_enabled = true

# Level of feed-specific logging
log_level = "info"

# Use the following fields to customize the feed's metadata
# (see https://help.apple.com/itc/podcasts_connect/#/itc1723472cb for details)
  [feeds.ID1.custom]
  cover_art = "{IMAGE_URL}"
  cover_art_quality = "high"
  subcategories = ["Documentary", "Tech News"]
  lang = "en"
  
  ownerName = "Simon Yost"
  ownerEmail = "simon@catchfire.show"

# Podcast title
title = "Catch Fire Show with Simon Yost" # change this to your desired podcast title

# Podcast description
description = "A podcast of my favorite YouTube playlist" # change this to your desired podcast description

# Podcast author
author = "Simon Yost (simon@catchfire.show)"

# Podcast language (ISO 639-1 code)
language = "en" # change this to your desired podcast language

# Podcast category (Apple Podcasts category code)
category = "TV & Film" # change this to your desired podcast category

# Podcast explicit content flag (true or false)
explicit = false
